import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Bot, Check, Copy, LoaderCircle, Paperclip, Pause, Play, Send, UserRound, X } from 'lucide-react';
import type { ToastType } from '../../lib/types';
import { api } from '../../lib/api';

type Props={showToast:(message:string,type?:ToastType)=>void};
type Attachment={id:number;file_name:string;content_type:string;size_bytes:number;preview_url:string;public_url?:string};
const filters=[['all','All'],['unread','Unread'],['needs_shaun','Needs Shaun'],['ai','AI Handling'],['human','Human Handling'],['failed','Failed'],['opted_out','Opted Out']];
const primary='inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';
const secondary='inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';

function messageAttachments(message:any):Attachment[]{try{return message.attachments_json?JSON.parse(message.attachments_json):[]}catch{return[]}}

export function CommunicationsPage({showToast}:Props){
  const [status,setStatus]=useState<any>(null),[conversations,setConversations]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[messages,setMessages]=useState<any[]>([]);
  const [filter,setFilter]=useState('all'),[draft,setDraft]=useState(''),[attachments,setAttachments]=useState<Attachment[]>([]),[uploading,setUploading]=useState(false),[busy,setBusy]=useState(false);
  const [sim,setSim]=useState('Looks good. How much?'),[simScenario,setSimScenario]=useState<'inbound'|'optout'|'duplicate'|'delivered'|'failed'|'network_error'|'status_duplicate'>('inbound');
  const [scripts,setScripts]=useState<any[]>([]),[showSetup,setShowSetup]=useState(false),[showScripts,setShowScripts]=useState(false);
  const load=useCallback(async()=>{try{const [s,c]=await Promise.all([api.messaging.status(),api.messaging.conversations(filter)]);setStatus(s);setConversations(c.conversations);if(selected){const d=await api.messaging.conversation(selected.id);setSelected(d.conversation);setMessages(d.messages)}}catch(e){showToast((e as Error).message,'error')}},[filter,selected?.id]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer)},[load]);
  useEffect(()=>{if(showScripts)void api.messaging.scripts().then((r:any)=>setScripts(r.scripts))},[showScripts]);
  async function open(c:any){const d=await api.messaging.conversation(c.id);setSelected(d.conversation);setMessages(d.messages);setAttachments([])}
  async function command(action:string){setBusy(true);try{await api.messaging.control({action} as any);await load()}catch(e){showToast((e as Error).message,'error')}finally{setBusy(false)}}
  async function conversationAction(action:string){await api.messaging.action(selected.id,action);await load()}
  async function send(){if(!draft.trim()&&!attachments.length)return;setBusy(true);try{await api.messaging.send(selected.id,draft.trim(),attachments.map(a=>a.id));setDraft('');setAttachments([]);await load()}catch(e){showToast((e as Error).message,'error')}finally{setBusy(false)}}
  async function uploadAttachment(file:File){if(attachments.reduce((total,item)=>total+item.size_bytes,0)+file.size>5*1024*1024){showToast('Combined MMS attachments must be 5 MB or smaller','error');return}setUploading(true);try{const r=await api.messaging.uploadAttachment(selected.id,file);setAttachments(a=>[...a,r.attachment]);showToast('Image attached','success')}catch(e){showToast((e as Error).message,'error')}finally{setUploading(false)}}
  async function removeAttachment(id:number){try{await api.messaging.deleteAttachment(id);setAttachments(a=>a.filter(item=>item.id!==id))}catch(e){showToast((e as Error).message,'error')}}
  async function retry(id:number){try{await api.messaging.retry(id);showToast('Retry sent','success');await load()}catch(e){showToast((e as Error).message,'error')}}
  async function resetConversation(){if(!selected||selected.is_test!==1||!window.confirm(`Reset only this test conversation with ${selected.company||selected.phone_number}?`))return;await api.messaging.resetTestConversation(selected.id);setSelected(null);setMessages([]);setAttachments([]);showToast('Test conversation reset','success');await load()}
  const ctl=status?.control,setup=status?.setup;
  return <div className="main space-y-4">
    {ctl?.mode==='test'&&<div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900">TEST MODE · No messages will be sent to real prospects.</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold tracking-wider text-slate-400">MESSAGING EMPLOYEE</div><div className="mt-1 flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${ctl?.status==='active'?'bg-emerald-500':'bg-slate-300'}`}/><span className="font-bold uppercase">{ctl?.status||'OFF'}</span><span className="rounded bg-slate-100 px-2 py-1 text-xs font-semibold uppercase">{ctl?.mode||'test'} / {ctl?.transport||'mock'}</span></div></div>
        <div className="flex flex-wrap gap-2"><button className={primary} disabled={busy} onClick={()=>command(ctl?.status==='paused'?'resume':'start')}><Play className="h-4 w-4"/>{ctl?.status==='paused'?'Resume employee':'Start employee'}</button><button className={secondary} onClick={()=>command('pause')}><Pause className="h-4 w-4"/>Pause</button><button className={secondary} onClick={()=>command('stop')}>Stop</button><button className={secondary} onClick={()=>setShowSetup(v=>!v)}>Setup</button><button className={secondary} onClick={()=>setShowScripts(v=>!v)}>Scripts</button></div></div>
      <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-6">{[['Ready to Send',status?.readyToSend],['Sent Today',status?.metrics?.sent_today],['Replies Today',status?.metrics?.replies_today],['AI Responded',status?.metrics?.ai_responded],['Needs Shaun',status?.metrics?.needs_shaun],['Failed',status?.metrics?.failed]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{label}</div><div className="text-2xl font-bold">{value||0}</div></div>)}</div>
      <div className="mt-4 flex flex-wrap gap-2"><select className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm font-medium text-slate-700 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" value={ctl?.mode||'test'} onChange={async e=>{try{const mode=e.target.value as 'test'|'production';await api.messaging.control(mode==='production'?{mode,transport:'twilio'}:{mode});await load()}catch(err){showToast((err as Error).message,'error')}}}><option value="test">Test mode</option><option value="production">Production</option></select><select className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm font-medium text-slate-700 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" value={ctl?.transport||'mock'} onChange={async e=>{try{await api.messaging.control({transport:e.target.value as any});await load()}catch(err){showToast((err as Error).message,'error');await load()}}}><option value="mock">Mock transport</option><option value="twilio">Live Twilio</option></select><button disabled={ctl?.status!=='active'||busy} className={primary} onClick={async()=>{setBusy(true);try{const r=await api.messaging.run();showToast(`${r.sent} sent; ${r.skipped||0} already sent; ${r.failed} failed`,'success');await load()}catch(e){showToast((e as Error).message,'error')}finally{setBusy(false)}}}><Send className="h-4 w-4"/>Process ready queue</button></div>
    </section>
    {showSetup&&<Setup setup={setup} ready={status?.productionReady} onTest={async()=>{try{await api.messaging.testSend();showToast('Test SMS sent — reply to verify the inbound webhook','success')}catch(e){showToast((e as Error).message,'error')}}}/>} {showScripts&&<Scripts scripts={scripts} onSave={async s=>{await api.messaging.saveScript(s.script_key,s.body||'',!!s.approved);showToast('Script saved','success')}}/>}
    <section className="grid min-h-[620px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[300px_minmax(380px,1fr)_280px]">
      <aside className="border-r border-slate-200"><div className="flex gap-1 overflow-x-auto border-b p-3">{filters.map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`whitespace-nowrap rounded-full px-2.5 py-1 text-xs ${filter===key?'bg-slate-900 text-white':'bg-slate-100 text-slate-700 hover:bg-slate-200'}`}>{label}</button>)}</div><div className="max-h-[560px] overflow-y-auto">{conversations.map(c=><button key={c.id} onClick={()=>open(c)} className={`w-full border-b p-4 text-left transition hover:bg-slate-50 ${selected?.id===c.id?'bg-blue-50':''}`}><div className="flex justify-between gap-2"><strong className="truncate text-sm">{c.company||c.phone_number}</strong><span className="text-[11px] text-slate-400">{c.unread_count?`${c.unread_count} new`:''}</span></div><div className="text-xs text-slate-500">{c.contact||c.phone_number}</div><p className="mt-1 truncate text-xs text-slate-500">{c.last_body}</p><div className="mt-2 flex gap-1">{c.needs_human===1&&<span className="rounded bg-amber-100 px-2 py-0.5 text-[10px] font-bold text-amber-800">Needs Shaun</span>}{c.has_failed===1&&<span className="rounded bg-red-100 px-2 py-0.5 text-[10px] font-bold text-red-700">Failed</span>}</div></button>)}</div></aside>
      <main className="flex min-w-0 flex-col"><div className="border-b p-4"><strong>{selected?.company||selected?.phone_number||'Select a conversation'}</strong>{selected?.ai_mode==='human'&&<div className="mt-1 text-xs font-semibold text-blue-700">YOU ARE HANDLING THIS CONVERSATION · AI responses are paused.</div>}</div><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-5">{messages.map(m=><div key={m.id} className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${m.direction==='outbound'?'ml-auto bg-blue-600 text-white':'bg-white shadow-sm'}`}>{messageAttachments(m).map(a=><img key={a.id} src={a.preview_url||a.public_url} alt={a.file_name} className="mb-2 max-h-64 rounded-lg object-contain"/>)}{m.body&&<div>{m.body}</div>}<div className={`mt-1 text-[10px] ${m.direction==='outbound'?'text-blue-100':'text-slate-400'}`}>{m.sent_by} · {m.twilio_status} · {new Date(m.created_at+'Z').toLocaleString()}</div>{m.twilio_error_description&&<div className="mt-1 text-xs text-red-200">{m.twilio_error_description}</div>}{m.direction==='outbound'&&['failed','undelivered'].includes(m.twilio_status)&&<button onClick={()=>retry(m.id)} className="mt-2 rounded-lg bg-white px-3 py-1.5 text-xs font-bold text-red-700 shadow-sm">Retry send</button>}</div>)}</div>
        {selected&&<div className="border-t border-slate-200 bg-white p-3">{attachments.length>0&&<div className="mb-3 flex flex-wrap gap-2">{attachments.map(a=><div key={a.id} className="relative overflow-hidden rounded-lg border border-slate-200 bg-slate-50"><img src={a.preview_url} alt={a.file_name} className="h-20 w-20 object-cover"/><button aria-label={`Remove ${a.file_name}`} onClick={()=>removeAttachment(a.id)} className="absolute right-1 top-1 rounded-full bg-slate-900/80 p-1 text-white hover:bg-slate-900"><X className="h-3 w-3"/></button></div>)}</div>}<div className="flex items-end gap-2"><label className={`${secondary} shrink-0 cursor-pointer`} title="Attach image">{uploading?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Paperclip className="h-4 w-4"/>}<span>Attach</span><input type="file" accept="image/jpeg,image/png,image/gif" className="sr-only" disabled={uploading||attachments.length>=10} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadAttachment(file);e.currentTarget.value=''}}/></label><textarea value={draft} onChange={e=>setDraft(e.target.value)} className="min-h-10 flex-1 resize-none rounded-lg border border-slate-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" placeholder="Type a message…"/><button onClick={send} disabled={busy||uploading||(!draft.trim()&&!attachments.length)} className={primary}><Send className="h-4 w-4"/>Send</button></div><p className="mt-2 text-[11px] text-slate-400">Attach up to 10 JPEG, PNG, or GIF images. Combined MMS limit: 5 MB.</p></div>}
      </main>
      <aside className="border-l border-slate-200 p-4"><h3 className="font-bold">Lead Context</h3>{selected?<div className="mt-4 space-y-3 text-sm"><Field label="Business" value={selected.company}/><Field label="Contact" value={selected.contact}/><Field label="Phone" value={selected.phone_number}/><Field label="Pipeline" value={selected.pipeline_status}/><Field label="Clarity" value={selected.engagement_score}/><Field label="AI mode" value={selected.ai_mode}/>{(selected.sms_suppressed===1||selected.status==='closed')&&<div className="rounded-lg bg-red-50 p-3 text-xs font-semibold text-red-700">SMS opted out<br/>{selected.is_test===1?'Test conversation only':selected.sms_suppression_reason}</div>}<button className={`${secondary} w-full`} onClick={()=>conversationAction(selected.ai_mode==='human'?'return_to_ai':'take_over')}>{selected.ai_mode==='human'?<Bot className="h-4 w-4"/>:<UserRound className="h-4 w-4"/>}{selected.ai_mode==='human'?'Return to AI':'Take over'}</button><button className={`${secondary} w-full`} onClick={()=>conversationAction(selected.needs_human?'clear_needs_shaun':'mark_needs_shaun')}>{selected.needs_human?'Clear Needs Shaun':'Mark Needs Shaun'}</button>{selected.site_url&&<a className={`${secondary} w-full`} href={selected.site_url} target="_blank" rel="noreferrer">Open demo</a>}<button className={`${secondary} w-full text-red-700`} disabled={selected.sms_suppressed===1||selected.status==='closed'} onClick={()=>conversationAction('suppress_sms')}>Suppress SMS</button></div>:<p className="mt-4 text-sm text-slate-500">Choose a thread to see lead context.</p>}
        <div className="mt-8 border-t pt-4"><div className="text-xs font-bold text-slate-500">TEST CONVERSATION</div><select value={simScenario} onChange={e=>setSimScenario(e.target.value as typeof simScenario)} className="mt-2 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-xs"><option value="inbound">Incoming reply</option><option value="optout">Opt-out / STOP</option><option value="duplicate">Duplicate inbound webhook</option><option value="status_duplicate">Duplicate status callback</option><option value="delivered">Delivered status</option><option value="failed">Bad number / landline failure</option><option value="network_error">Provider network error</option></select>{(simScenario==='inbound'||simScenario==='duplicate')&&<textarea value={sim} onChange={e=>setSim(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-xs"/>}<button className={`${secondary} mt-2 w-full`} onClick={async()=>{const r=await api.messaging.simulate(sim,selected?.lead_id,simScenario);await load();await open({id:r.conversationId})}}>Run simulation</button>{selected?.is_test===1&&<button className="mt-2 inline-flex h-9 w-full items-center justify-center rounded-lg border border-red-200 bg-white px-3 text-xs font-semibold text-red-700 hover:bg-red-50" onClick={resetConversation}>Reset this conversation</button>}</div>
      </aside>
    </section>
  </div>
}

function Field({label,value}:{label:string;value:any}){return <div><div className="text-xs text-slate-400">{label}</div><div className="font-medium">{value??'—'}</div></div>}
function Setup({setup,ready,onTest}:{setup:any;ready:boolean;onTest:()=>void}){const rows=[['Twilio Account SID',setup?.accountSid,'Set TWILIO_ACCOUNT_SID as a Worker secret.'],['Twilio Auth Token',setup?.authToken,'Set TWILIO_AUTH_TOKEN as a Worker secret.'],['Messaging Service',setup?.messagingService,'Create a Twilio Messaging Service, add the sender, then set TWILIO_MESSAGING_SERVICE_SID.'],['Business SMS number',setup?.phoneNumber,'Set TWILIO_PHONE_NUMBER to the sender attached to that service.'],['A2P registration',setup?.a2pRegistered,'Complete registration in Twilio, then set TWILIO_A2P_REGISTERED=true.'],['Test mobile number',setup?.testNumber,'Set TEST_SMS_NUMBER_1 to Shaun’s mobile number.']];return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">SHAUN SETUP REQUIRED</h2><p className={`mt-1 text-sm ${ready?'text-emerald-700':'text-amber-700'}`}>{ready?'Production configuration is complete.':'Production remains locked until every required item is complete.'}</p><div className="mt-4 grid gap-2">{rows.map(([name,ok,detail])=><div className="flex gap-3 rounded-lg bg-slate-50 p-3" key={String(name)}>{ok?<Check className="h-5 w-5 text-emerald-600"/>:<AlertTriangle className="h-5 w-5 text-amber-600"/>}<div><div className="text-sm font-semibold">{name}</div>{!ok&&<div className="text-xs text-slate-500">{detail}</div>}</div></div>)}</div>{[['Incoming Messages',setup?.inboundUrl],['Status Callback',setup?.statusUrl]].map(([label,url])=><button key={label} className={`${secondary} mt-3 mr-2`} onClick={()=>navigator.clipboard.writeText(url||'')}><Copy className="h-3 w-3"/>{label}: {url}</button>)}<button className={`${primary} mt-3`} disabled={!setup?.testNumber||!setup?.messagingService} onClick={onTest}>Send test SMS</button></section>}
function Scripts({scripts,onSave}:{scripts:any[];onSave:(s:any)=>void}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Messaging Scripts</h2><p className="mt-1 text-xs text-slate-500">Canonical copy reused from Text Outreach and the Call Center playbook. The exact source is shown on each card.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{scripts.map(s=>{const noAutoReply=['not_interested','human_escalation'].includes(s.script_key);return <div key={s.script_key} className="rounded-xl border p-3"><div className="flex items-center justify-between"><strong className="text-sm">{s.label}</strong>{noAutoReply?<span className="text-[10px] font-bold text-slate-500">NO AUTO-REPLY</span>:!s.approved&&<span className="text-[10px] font-bold text-amber-700">REQUIRES SHAUN APPROVAL</span>}</div>{s.source_reference&&<div className="mt-1 text-[10px] text-slate-400">Source: {s.source_reference}</div>}<textarea className="mt-2 min-h-24 w-full rounded-lg border border-slate-300 p-2 text-xs" defaultValue={s.body||''} disabled={noAutoReply} onChange={e=>s.body=e.target.value}/>{!noAutoReply&&<><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" defaultChecked={!!s.approved} onChange={e=>s.approved=e.target.checked}/>Approved</label><button className={`${secondary} mt-2`} onClick={()=>onSave(s)}>Save script</button></>}</div>})}</div></section>}
